### ISSUE TITLE
v1.11.6 failed to build jitpack

### ISSUE THREAD

**Issue by rexlManu** [Jannyboy11/GuiLib#6]
Hey,

i saw that the newest version of your library didnt build successful.
You should check that.

https://jitpack.io/com/github/Jannyboy11/GuiLib/v1.11.6/build.log

Thank you!

**Comment by Jannyboy11** [comment]
Interesting. It built just fine locally. Although I do see that I forgot to update the project versions in the poms, that shouldn't matter because jitpack uses git tags.

Looking at the build log, it says
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for GuiLib 1.11.5:
[INFO] 
[INFO] GuiLib ............................................. SUCCESS [  6.838 s]
[INFO] GuiLib-API ......................................... SUCCESS [ 10.737 s]
[INFO] GuiLib-Plugin ...................................... SUCCESS [  2.626 s]
[INFO] GuiLib-Examples .................................... SUCCESS [  1.242 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.446 s
[INFO] Finished at: 2021-06-03T16:14:42Z
[INFO] ------------------------------------------------------------------------
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: xyz.janboerman:GuiLib:1.11.5
ERROR: Time-out getting container status
Error building
```
at the end - meaning that compiling the whole thing went just fine, but for some reason the jitpack's script could not get the container's status. This is not something I control, so my best option to 'fix' this is to just commit a new tag and see if it works again then.

**Comment by Jannyboy11** [comment]
You can now use ~~1.11.6~~ v1.11.7 as the version in the dependency.
